### ISSUE TITLE
Getting an error when attempting to finetune Mixtral

### ISSUE THREAD

**Issue by jagilley** [mistralai/mistral-finetune#23]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/mistral-finetune/utils/validate_data.py", line 366, in <module>
    main(args)
  File "/workspace/mistral-finetune/utils/validate_data.py", line 315, in main
    expected_stats = get_train_stats(
  File "/workspace/mistral-finetune/utils/validate_data.py", line 98, in get_train_stats
    (Path(train_args.model_id_or_path) / "params.json").open()
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/mistral-finetune/mixtral/params.json'
```

I downloaded the model directly from `https://huggingface.co/mistralai/Mixtral-8x7B-v0.1`. It seems that implementation lacks the `params.json` file.

**Comment by C3po-D2rd2** [comment]
hello,
  Did you solve this issue?

**Comment by C3po-D2rd2** [comment]
Alrights for noobs like me, you just need to set in example/7B.yaml the model_id_or_path to the directory where you downloaded data

**Comment by juliendenize** [comment]
Hi! We're archiving this repository as it's no longer actively maintained, and therefore this issue is being closed.
